### ISSUE TITLE
Great library, but...

### ISSUE THREAD

**Issue by cwbeck** [m3dev/curly#8]
Are there any more docs to using this with futures?

val future: Future[Response] = HTTP.asyncGet("http://www.example.com");

Not 100% clear how to implement from here for getting the response back.

**Comment by seratch** [comment]
The `Future` is the Scala standard API. See http://www.scala-lang.org/api/2.11.7/index.html#scala.concurrent.Future.

**Comment by cwbeck** [comment]
Thanks for the reply, I've used futures, but only in a simple way to date. I can't seem to apply the same style to this:

    val f: Future[Response] = HTTP.asyncGet("http://www.google.com")
    f.onComplete({
      case Success(response) => println(response.headers())
      case Failure(e) => println("failed...")
    })
    while(!f.isCompleted){
      //run...
    }
    println("exiting...")

I simply get...

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
exiting...

Process finished with exit code 0

Any help here I would be extremely grateful :)

**Comment by seratch** [comment]
Doing like this will make your example more stable.

```scala
Thead.sleep(10)
println("exiting...")
```

**Comment by cwbeck** [comment]
Brilliant. Thanks, I knew I was missing something simple!

**Comment by seratch** [comment]
Glad to hear that :smile:  Let me close this issue. Thanks.
